apiVersion: cloud-build-notifiers/v1
kind: SMTPNotifier
metadata:
  name: example-smtp-notifier
spec:
  notification:
    filter: build.status == Build.Status.PENDING
    params:
      buildStatus: $(build.status)
    delivery:
      server: smtp.gmail.com
      port: "587"
      sender: dev@cisdi.org
      from: dev@cisdi.org
      recipients:
        - kiki.hutapea@cisdi.org
        # optional: more emails here
      password:
        secretRef: smtp-password
    template:
      type: golang
      uri: gs://cisdi-cloud-build-notifier-bkt/cloud-build-ops-template.html
  secrets:
  - name: smtp-password
    value: projects/261319966299/secrets/dev-cisdi-org-email-app-password/versions/1