apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: cloudbuild-slack-notifier
spec:
  notification:
    filter: build.status in [Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.TIMEOUT, Build.Status.PENDING] && build.substitutions["TRIGGER_NAME"].matches("^sii-.*-ci.*$") && build.substitutions["_APP_ROLE"] != "user-interface"
    params:
      buildStatus: $(build.status)
      triggerName: $(build.substitutions.TRIGGER_NAME)
      commitID: $(build.substitutions.COMMIT_SHA)
      appRole: $(build.substitutions._APP_ROLE)
    delivery:
      webhookUrl:
        secretRef: webhook-url
    template:
      type: golang
      uri: gs://cloud-operations-cisdi-bkt/cloud-build-notifier/slack/sii-monitoring/slack.json
  secrets:
  - name: webhook-url
    value: projects/453378925845/secrets/slackapp-webhook-url/versions/sii-monitoring